package com.ranga.entity;
// Generated 15.05.2018 1:29:21 by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Dynamics generated by hbm2java
 */
public class Dynamics implements java.io.Serializable {

	private Long id;
	private long idUser;
	private float weight;
	private Date dtweight;

	public Dynamics() {
	}

	public Dynamics(long idUser, float weight, Date dtweight) {
		this.idUser = idUser;
		this.weight = weight;
		this.dtweight = dtweight;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getIdUser() {
		return this.idUser;
	}

	public void setIdUser(long idUser) {
		this.idUser = idUser;
	}

	public float getWeight() {
		return this.weight;
	}

	public void setWeight(float weight) {
		this.weight = weight;
	}

	public Date getDtweight() {
		return this.dtweight;
	}

	public void setDtweight(Date dtweight) {
		this.dtweight = dtweight;
	}

}
