package com.ranga.entity;
// Generated 15.05.2018 1:29:21 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Food generated by hbm2java
 */
public class Food implements java.io.Serializable {

	private Long id;
	private Category category;
	private String name;
	private float kkal;
	private Float protein;
	private Float fat;
	private Float carbs;
	private Date updated;
	private Set mealses = new HashSet(0);

	public Food() {
	}

	public Food(Category category, String name, float kkal) {
		this.category = category;
		this.name = name;
		this.kkal = kkal;
	}

	public Food(Category category, String name, float kkal, Float protein, Float fat, Float carbs, Date updated,
			Set mealses) {
		this.category = category;
		this.name = name;
		this.kkal = kkal;
		this.protein = protein;
		this.fat = fat;
		this.carbs = carbs;
		this.updated = updated;
		this.mealses = mealses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public float getKkal() {
		return this.kkal;
	}

	public void setKkal(float kkal) {
		this.kkal = kkal;
	}

	public Float getProtein() {
		return this.protein;
	}

	public void setProtein(Float protein) {
		this.protein = protein;
	}

	public Float getFat() {
		return this.fat;
	}

	public void setFat(Float fat) {
		this.fat = fat;
	}

	public Float getCarbs() {
		return this.carbs;
	}

	public void setCarbs(Float carbs) {
		this.carbs = carbs;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public Set getMealses() {
		return this.mealses;
	}

	public void setMealses(Set mealses) {
		this.mealses = mealses;
	}

}
