package com.ranga.entity;
// Generated 15.05.2018 1:29:21 by Hibernate Tools 5.1.7.Final

import java.util.Date;

/**
 * Meals generated by hbm2java
 */
public class Meals implements java.io.Serializable {

	private Long id;
	private Food food;
	private Mealtypes mealtypes;
	private Units units;
	private User user;
	private Date dtmeal;
	private float amount;
	private float kkal;

	public Meals() {
	}

	public Meals(Food food, Mealtypes mealtypes, Units units, User user, Date dtmeal, float amount, float kkal) {
		this.food = food;
		this.mealtypes = mealtypes;
		this.units = units;
		this.user = user;
		this.dtmeal = dtmeal;
		this.amount = amount;
		this.kkal = kkal;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Food getFood() {
		return this.food;
	}

	public void setFood(Food food) {
		this.food = food;
	}

	public Mealtypes getMealtypes() {
		return this.mealtypes;
	}

	public void setMealtypes(Mealtypes mealtypes) {
		this.mealtypes = mealtypes;
	}

	public Units getUnits() {
		return this.units;
	}

	public void setUnits(Units units) {
		this.units = units;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getDtmeal() {
		return this.dtmeal;
	}

	public void setDtmeal(Date dtmeal) {
		this.dtmeal = dtmeal;
	}

	public float getAmount() {
		return this.amount;
	}

	public void setAmount(float amount) {
		this.amount = amount;
	}

	public float getKkal() {
		return this.kkal;
	}

	public void setKkal(float kkal) {
		this.kkal = kkal;
	}

}
