package com.ranga.entity;
// Generated 15.05.2018 1:29:21 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Mealtypes generated by hbm2java
 */
public class Mealtypes implements java.io.Serializable {

	private Long id;
	private String name;
	private Set mealses = new HashSet(0);

	public Mealtypes() {
	}

	public Mealtypes(String name) {
		this.name = name;
	}

	public Mealtypes(String name, Set mealses) {
		this.name = name;
		this.mealses = mealses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getMealses() {
		return this.mealses;
	}

	public void setMealses(Set mealses) {
		this.mealses = mealses;
	}

}
