package com.ranga.entity;
// Generated 15.05.2018 1:29:21 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Statuses generated by hbm2java
 */
public class Statuses implements java.io.Serializable {

	private Long id;
	private String name;
	private Set users = new HashSet(0);

	public Statuses() {
	}

	public Statuses(String name, Set users) {
		this.name = name;
		this.users = users;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
