package com.ranga.entity;
// Generated 15.05.2018 1:29:21 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Units generated by hbm2java
 */
public class Units implements java.io.Serializable {

	private Long id;
	private String name;
	private Float pergramms;
	private String shortname;
	private Set mealses = new HashSet(0);

	public Units() {
	}

	public Units(String name) {
		this.name = name;
	}

	public Units(String name, Float pergramms, String shortname, Set mealses) {
		this.name = name;
		this.pergramms = pergramms;
		this.shortname = shortname;
		this.mealses = mealses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Float getPergramms() {
		return this.pergramms;
	}

	public void setPergramms(Float pergramms) {
		this.pergramms = pergramms;
	}

	public String getShortname() {
		return this.shortname;
	}

	public void setShortname(String shortname) {
		this.shortname = shortname;
	}

	public Set getMealses() {
		return this.mealses;
	}

	public void setMealses(Set mealses) {
		this.mealses = mealses;
	}

}
